// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelWeb_API.Models.Itinerary.DBModel;

public partial class ActivityMapping
{
    public int MappingId { get; set; }

    public string ActivityId { get; set; }

    public int ItineraryId { get; set; }

    public DateTime? CreateTime { get; set; }

    public virtual Itinerary Itinerary { get; set; }
}