// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelWeb_API.Models.Itinerary.DBModel;

public partial class AigenerationError
{
    public int ErrorId { get; set; }

    public int? ItineraryId { get; set; }

    public int? VersionId { get; set; }

    public string ErrorType { get; set; }

    public string SeverityLevel { get; set; }

    public string ErrorMessage { get; set; }

    public string ErrorReason { get; set; }

    public string AdminResponse { get; set; }

    public int? RelatedItemId { get; set; }

    public bool? IsConfirmed { get; set; }

    public DateTime? CreateTime { get; set; }

    public virtual Itinerary Itinerary { get; set; }

    public virtual ItineraryItem RelatedItem { get; set; }

    public virtual ItineraryVersion Version { get; set; }
}