// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelWeb_API.Models.Itinerary.DBModel;

public partial class Attraction
{
    public int AttractionId { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public int RegionId { get; set; }

    public string? AreaId { get; set; }

    public int? ApprovalStatus { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public string OpendataId { get; set; }

    public string Phone { get; set; }

    public string Website { get; set; }

    public string BusinessHours { get; set; }

    public string GooglePlaceId { get; set; }

    public string ClosedDaysNote { get; set; }

    public string TransportInfo { get; set; }

    public DateTime CreatedAt { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<ItineraryItem> ItineraryItems { get; set; } = new List<ItineraryItem>();
}