// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelWeb_API.Models.Itinerary.DBModel;

public partial class Itinerary
{
    public int ItineraryId { get; set; }

    public string MemberId { get; set; }

    public string ItineraryName { get; set; }

    public string ItineraryImage { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string Introduction { get; set; }

    public DateTime? CreateTime { get; set; }

    public string CurrentStatus { get; set; }

    public virtual ICollection<ActivityMapping> ActivityMappings { get; set; } = new List<ActivityMapping>();

    public virtual ICollection<AigenerationError> AigenerationErrors { get; set; } = new List<AigenerationError>();

    public virtual ICollection<ItineraryVersion> ItineraryVersions { get; set; } = new List<ItineraryVersion>();
}