// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelWeb_API.Models.Itinerary.DBModel;

public partial class ItineraryComparison
{
    public int ComparisonId { get; set; }

    public int OriginalVersionId { get; set; }

    public int ComparedVersionId { get; set; }

    public DateTime? ComparisonTime { get; set; }

    public virtual ItineraryVersion ComparedVersion { get; set; }

    public virtual ItineraryVersion OriginalVersion { get; set; }
}