// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace TravelWeb_API.Models.Itinerary.DBModel;

public partial class ItineraryItem
{
    public int ItemId { get; set; }

    public int? AttractionId { get; set; }

    public int VersionId { get; set; }

    public int? DayNumber { get; set; }

    public string ContentDescription { get; set; }

    public int? SortOrder { get; set; }

    public string ActivityId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string? GooglePlaceId { get; set; }

    public string? AttractionName { get; set; }

    public virtual ICollection<AigenerationError> AigenerationErrors { get; set; } = new List<AigenerationError>();

    public virtual Attraction Attraction { get; set; }

    public virtual ItineraryVersion Version { get; set; }
}