// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using TravelWeb_API.Models.Itinerary.DBModel;

namespace TravelWeb_API.Models.Itinerary.DBContext;

public partial class TravelContext : DbContext
{
    public TravelContext(DbContextOptions<TravelContext> options)
        : base(options)
    {
    }

    public virtual DbSet<ActivityMapping> ActivityMappings { get; set; }

    public virtual DbSet<Aianalysis> Aianalyses { get; set; }

    public virtual DbSet<AigenerationError> AigenerationErrors { get; set; }

    public virtual DbSet<Attraction> Attractions { get; set; }

    public virtual DbSet<DBModel.Itinerary> Itineraries { get; set; }

    public virtual DbSet<ItineraryComparison> ItineraryComparisons { get; set; }

    public virtual DbSet<ItineraryItem> ItineraryItems { get; set; }

    public virtual DbSet<ItineraryVersion> ItineraryVersions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<ActivityMapping>(entity =>
        {
            entity.HasKey(e => e.MappingId).HasName("PK__Activity__8B5781BD04E800C6");

            entity.ToTable("ActivityMapping", "Itinerary");

            entity.Property(e => e.MappingId).HasColumnName("MappingID");
            entity.Property(e => e.ActivityId)
                .IsRequired()
                .HasMaxLength(50)
                .HasColumnName("ActivityID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ItineraryId).HasColumnName("ItineraryID");

            entity.HasOne(d => d.Itinerary).WithMany(p => p.ActivityMappings)
                .HasForeignKey(d => d.ItineraryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_ActivityMapping_Itineraries");
        });

        modelBuilder.Entity<Aianalysis>(entity =>
        {
            entity.HasKey(e => e.AnalysisId).HasName("PK__AIAnalys__5B789DE89E5C3867");

            entity.ToTable("AIAnalyses", "Itinerary");

            entity.Property(e => e.AnalysisId).HasColumnName("AnalysisID");
            entity.Property(e => e.AnalysisTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.FatigueIndex).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.FeasibilityScore).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.PaceBalanceScore).HasColumnType("decimal(5, 2)");
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.Version).WithMany(p => p.Aianalyses)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__AIAnalyse__Versi__57DD0BE4");
        });

        modelBuilder.Entity<AigenerationError>(entity =>
        {
            entity.HasKey(e => e.ErrorId).HasName("PK__AIGenera__358565CACDCE448F");

            entity.ToTable("AIGenerationErrors", "Itinerary");

            entity.Property(e => e.ErrorId).HasColumnName("ErrorID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasAnnotation("Relational:DefaultConstraintName", "DF__AIGenerat__Creat__540C7B00")
                .HasColumnType("datetime");
            entity.Property(e => e.ErrorType).HasMaxLength(50);
            entity.Property(e => e.IsConfirmed)
                .HasDefaultValue(false)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__AIGenerat__IsCon__531856C7");
            entity.Property(e => e.ItineraryId).HasColumnName("ItineraryID");
            entity.Property(e => e.RelatedItemId).HasColumnName("RelatedItemID");
            entity.Property(e => e.SeverityLevel).HasMaxLength(50);
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.Itinerary).WithMany(p => p.AigenerationErrors)
                .HasForeignKey(d => d.ItineraryId)
                .HasConstraintName("FK_AIGenerationErrors_Itineraries");

            entity.HasOne(d => d.RelatedItem).WithMany(p => p.AigenerationErrors)
                .HasForeignKey(d => d.RelatedItemId)
                .HasConstraintName("FK_AIGenerationErrors_ItineraryItems");

            entity.HasOne(d => d.Version).WithMany(p => p.AigenerationErrors)
                .HasForeignKey(d => d.VersionId)
                .HasConstraintName("FK_AIGenerationErrors_ItineraryVersions");
        });

        modelBuilder.Entity<Attraction>(entity =>
        {
            entity.ToTable("Attractions", "Attractions");

            entity.Property(e => e.AttractionId).HasColumnName("attraction_id");
            entity.Property(e => e.Address)
                .HasMaxLength(255)
                .HasColumnName("address");
            entity.Property(e => e.ApprovalStatus)
                .HasDefaultValue(0)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Attractio__appro__7A3223E8")
                .HasColumnName("approval_status");
            entity.Property(e => e.AreaId)
                .HasMaxLength(50)
                .HasColumnName("area_id");
            entity.Property(e => e.BusinessHours)
                .HasMaxLength(500)
                .HasColumnName("business_hours");
            entity.Property(e => e.ClosedDaysNote)
                .HasMaxLength(200)
                .HasColumnName("closed_days_note");
            entity.Property(e => e.CreatedAt)
                .HasColumnType("datetime")
                .HasColumnName("created_at");
            entity.Property(e => e.GooglePlaceId)
                .HasMaxLength(255)
                .HasColumnName("google_place_id");
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");
            entity.Property(e => e.Latitude)
                .HasColumnType("decimal(10, 7)")
                .HasColumnName("latitude");
            entity.Property(e => e.Longitude)
                .HasColumnType("decimal(10, 7)")
                .HasColumnName("longitude");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.OpendataId)
                .HasMaxLength(100)
                .HasColumnName("opendata_id");
            entity.Property(e => e.Phone)
                .HasMaxLength(50)
                .HasColumnName("phone");
            entity.Property(e => e.RegionId)
                .HasAnnotation("Relational:DefaultConstraintName", "DF__Attractio__regio__793DFFAF")
                .HasColumnName("RegionID");
            entity.Property(e => e.TransportInfo).HasColumnName("transport_info");
            entity.Property(e => e.ViewCount).HasColumnName("view_count");
            entity.Property(e => e.Website)
                .HasMaxLength(500)
                .HasColumnName("website");
        });

        modelBuilder.Entity<DBModel.Itinerary>(entity =>
        {
            entity.HasKey(e => e.ItineraryId).HasName("PK__Itinerar__361216A6E8732ED0");

            entity.ToTable("Itineraries", "Itinerary");

            entity.Property(e => e.ItineraryId).HasColumnName("ItineraryID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CurrentStatus).HasMaxLength(50);
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.Introduction).HasMaxLength(500);
            entity.Property(e => e.ItineraryImage).HasMaxLength(1000);
            entity.Property(e => e.ItineraryName)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.MemberId)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.StartTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<ItineraryComparison>(entity =>
        {
            entity.HasKey(e => e.ComparisonId).HasName("PK__Itinerar__6E1F99B7545F294D");

            entity.ToTable("ItineraryComparisons", "Itinerary");

            entity.Property(e => e.ComparisonId).HasColumnName("ComparisonID");
            entity.Property(e => e.ComparedVersionId).HasColumnName("ComparedVersionID");
            entity.Property(e => e.ComparisonTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.OriginalVersionId).HasColumnName("OriginalVersionID");

            entity.HasOne(d => d.ComparedVersion).WithMany(p => p.ItineraryComparisonComparedVersions)
                .HasForeignKey(d => d.ComparedVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Itinerary__Compa__58D1301D");

            entity.HasOne(d => d.OriginalVersion).WithMany(p => p.ItineraryComparisonOriginalVersions)
                .HasForeignKey(d => d.OriginalVersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Itinerary__Origi__59C55456");
        });

        modelBuilder.Entity<ItineraryItem>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PK__Itinerar__727E83EBFABCDC81");

            entity.ToTable("ItineraryItems", "Itinerary");

            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.ActivityId)
                .HasMaxLength(50)
                .HasColumnName("ActivityID");
            entity.Property(e => e.AttractionId).HasColumnName("attraction_id");
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
            entity.Property(e => e.VersionId).HasColumnName("VersionID");

            entity.HasOne(d => d.Attraction).WithMany(p => p.ItineraryItems)
                .HasForeignKey(d => d.AttractionId)
                .HasConstraintName("FK_ItineraryItems_Attractions");

            entity.HasOne(d => d.Version).WithMany(p => p.ItineraryItems)
                .HasForeignKey(d => d.VersionId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Itinerary__Versi__5AB9788F");
        });

        modelBuilder.Entity<ItineraryVersion>(entity =>
        {
            entity.HasKey(e => e.VersionId).HasName("PK__Itinerar__16C6402F82939D88");

            entity.ToTable("ItineraryVersions", "Itinerary");

            entity.Property(e => e.VersionId).HasColumnName("VersionID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.CurrentUsageStatus).HasMaxLength(50);
            entity.Property(e => e.ItineraryId).HasColumnName("ItineraryID");
            entity.Property(e => e.Source).HasMaxLength(50);
            entity.Property(e => e.VersionRemark).HasMaxLength(500);

            entity.HasOne(d => d.Itinerary).WithMany(p => p.ItineraryVersions)
                .HasForeignKey(d => d.ItineraryId)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__Itinerary__Itine__5BAD9CC8");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}